### ISSUE TITLE
README Page "Installing" Section Error

### ISSUE THREAD

**Issue by sychoo** [gdsrosa/minimal_improved#4]
In the README.md file, under the "Installing" section, you have
```bash
$ vim ~/.zshrc
ZSH_THEME=minimal_improved
```
You forgot to put the double quotes around the "minimal_improved"
it should be
```bash
$ vim ~/.zshrc
ZSH_THEME="minimal_improved"
```

**Comment by gdsrosa** [comment]
Noice! Thanks man! 😎

**Comment by sychoo** [comment]
You're welcome! Thanks for the awesome theme. I've been using it for about 2 years now and I love it!
